name: cs236781-hw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # common
  - ffmpeg
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs>=12.0
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn=0.24.2
  - scipy
  - swig # needed to compile box2d
  - tqdm
  - pip:
    - nbmerge
    - gym[atari,accept-rom-license,box2d]==0.21.0
  # pytorch
  - pytorch=1.10.1
  - torchvision
  - torchtext

platforms:
  - linux-64
  